### ISSUE TITLE
Evaluate shortcomings of current integration design

### ISSUE THREAD

**Issue by mturilli** [ATLAS-Titan/PanDA-NGE#10]
Please collect them here while you think about them.

**Comment by mturilli** [comment]
* Ruslan: reviewed the design document.
* Difficult to support current ATLAS multi-job use case. The current PanDA Server installed on Titan is outdated to support it. This is due to the development and production infrastructure of ATLAS. It is not easy or possible to migrate this to the current back end installed on Titan.
* Today I met with PanDA people that suggested that a 4-months old PanDA Server could be use for the multi-job use case. I hope that in the next two days this use case will be supported.

**Comment by mturilli** [comment]
* Ruslan: The core ideas of the current design seem sound (yet, it is still quiet general) and I do not see major shortcomings.

**Comment by ruslan33** [comment]
- Testing multi-job pilot I stucked into the data stage-in/-out functions (they are experiment specific)
- I have returned back for a single-job pilot (As I'm more familiar with) and implemented the simple methods to run the jobs with input/output files. The implementation will be customised later.
- Currently I have a stable complete single-job pilot I can start with NGE implementation (NGE DB calls etc.)
- Will continue to adaptation for multi-job pilot as the common issue with stage-in/-out was solved

**Comment by mturilli** [comment]
Great! Do you host your code on a repository? If so, could we have read access to it?
