### ISSUE TITLE
Move the Gromacs use case to this repository

### ISSUE THREAD

**Issue by mturilli** [ATLAS-Titan/PanDA-NGE#11]

**Comment by mturilli** [comment]
@shantenujha should we use this use case as a reference: https://docs.google.com/document/d/1a8i38Z_aROQgylRNtbsePGH6UovRJgg0WW4gbk5kW4A/edit

**Comment by shantenujha** [comment]
@mturilli I believe this was the document in reference:
https://github.com/codar-bnl/md-workflows/wiki/Example-of-workload--execution-(multistage-pipelines)

**Comment by AA919** [comment]
For the moment we are running Gromacs only. LSDMap is not executed.

**Comment by mturilli** [comment]
Strong and weak scalability of this use case as validation of the design.

**Comment by AA919** [comment]
Files can be found in PanDA-NGE/NGE/
