### ISSUE TITLE
Evaluate polling/using Titan's Moab backfill information from NGE

### ISSUE THREAD

**Issue by mturilli** [ATLAS-Titan/PanDA-NGE#18]

**Comment by mturilli** [comment]
Ongoing. Ruslan to provide the command currently used in PanDA.

**Comment by ruslan33** [comment]
The command I'm using (on titan.ccs.ornl.gov machine) to get backfill info: `showbf --blocking -p titan`

**Comment by mturilli** [comment]
To evaluate for SC demo #25

**Comment by andre-merzky** [comment]
This is now implemented, and seems to work as expected.  The functionality is exposed in the api as `request_backfill_resources()` method, which triggers the `showbf` query and pilot submission.

Next step would be to implement some sensible backfilling *policy*.
