### ISSUE TITLE
Abstract away hardcoded allocation from NGE

### ISSUE THREAD

**Issue by mturilli** [ATLAS-Titan/PanDA-NGE#19]

**Comment by mturilli** [comment]
Andre to provide an updated API by Aug 8

**Comment by andre-merzky** [comment]
Ruslan, after checking the config we have for titan, I am not sure anymore why you stumbled over a project/allocation setting problem (it was that if I remember correctly?).  Would you mind pasting the actual error you found, and if possible also mail me any log files you found?  Thanks!

**Comment by andre-merzky** [comment]
implemented as shown [here](https://github.com/radical-cybertools/radical.pilot/blob/experiment/panda_nge/examples/misc/panda_nge.py#L20), needs testing.

**Comment by mturilli** [comment]
Ruslan tested and looks OK.
