### ISSUE TITLE
Security for HTTP service interface

### ISSUE THREAD

**Issue by andre-merzky** [ATLAS-Titan/PanDA-NGE#23]

**Comment by mturilli** [comment]
Use https://github.com/nickbabcock/bottle-ssl to secure the connection between PanDA Pilot and NGE. Security is not too much of a concern because we will work within the ORNL. SSL should work for PanDA Pilot too.

**Comment by mturilli** [comment]
Use login and password. #24 depends on this

**Comment by andre-merzky** [comment]
Cookie based user/pass auth is in place now.
