### ISSUE TITLE
Extend Gromacs use case with output files

### ISSUE THREAD

**Issue by mturilli** [ATLAS-Titan/PanDA-NGE#9]
Use case currently coded at: https://github.com/ATLAS-Titan/misc/tree/master/fireworks

**Comment by mturilli** [comment]
* Make the script to use a configuration file where to specify the shared file system and one or more locations. These will be used to save output files (and possibly read input files). 
* Use a tag for unit naming: avoid risk to override files.

**Comment by AA919** [comment]
Done
